debug:           false
db:
  username:     "postgres"
  userpassword: "mysecretpassword"
  host:         "localhost"
  port:         "5432"
  database:     "hackathondb"
host:
  ip:           "localhost"
  port:         "3000"
authhost:
  ip:           "localhost"
  port:         "3001"
auth:
  ip:           "localhost"
  port:         "3001"
  fbclient:     "297124087550852"
  fbsecret:     "02d79e1bb5d9753be5e6b815d8dfd45e"
