debug:           false
db:
  username:     "postgres"
  userpassword: "mysecretpassword"
  host:         "localhost"
  port:         "5432"
  database:     "hackathondb"
host:
  ip:           "localhost"
  port:         "3000"