version: '3'
services:
  postgres:
    image: kartoza/postgis:9.6-2.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: developer
      POSTGRES_DBNAME: cywdb
      POSTGRES_PASS: somepass
    volumes:
      - $HOME/data/postgres:/var/lib/postgresql/data
  redis:
    image: library/redis
    ports:
      - "6379:6379"
